### ISSUE TITLE
Problems with the TcpNoDelay option with two participants in WSL

### ISSUE THREAD

**Issue by MarcoJassy** [vectorgrp/sil-kit#149] opened 2024-11-19 18:18 UTC
Hello, I don't seem to be able to connect two participants in WSL with the TcpNoDelay option set to true. I receive the messages bellow every time I connect the second participant.

> [2024-11-19 15:06:15.087] [wsl_can_md] [info] Creating participant 'wsl_can_md' at 'silkit://0.0.0.0:8501', SIL Kit version: 4.0.42
> [2024-11-19 15:06:15.087] [wsl_can_md] [info] The provided registry URI 'silkit://localhost:8501' differs from the configured registry URI 'silkit://0.0.0.0:8501'. The latter will be used.
> [2024-11-19 15:06:15.088] [wsl_can_md] [info] Connected to registry at 'local:///tmp/SilKitRegibb27dfeaa022c81c.silkit' via 'local://' (local:///tmp/SilKitRegibb27dfeaa022c81c.silkit, silkit://0.0.0.0:8501)
**> [2024-11-19 15:06:15.088] [wsl_can_md] [warning] SetAsioSocketOptions: failed to enable 'no delay' option**
> [2024-11-19 15:06:15.091] [wsl_can_md] [error] SilKit-IOWorker: Something went wrong: basic_string::_M_create
> [2024-11-19 15:06:20.091] [wsl_can_md] [error] Timeout while waiting for replies from known participants: wsl_can_dn (tcp://127.0.0.1:8502) is waiting for reply
> Something went wrong: SIL Kit: An unspecified error occured. (1): Timeout while waiting for replies from known participants: wsl_can_dn (tcp://127.0.0.1:8502) is waiting for reply
> Press enter to stop the process...

I am using windows 10 with WSL2 and Ubuntu22.04.

Here is the configuration yaml of the participant:

```
schemaVersion: 1
Description: CANoe Configuration

Middleware:
  RegistryUri: silkit://0.0.0.0:8501
  ConnectAttempts: 1
  TcpNoDelay: true
  AcceptorUris: [tcp://0.0.0.0:8504]
  RegistryAsFallbackProxy: true

Logging:
  Sinks:
    - Type: Stdout
      Level: Info
```

Thanks in advance.

**Comment by MariusBgm** [comment] 2024-11-20 06:24
Hi @MarcoJassy,
the participant's configuration states taht the registry's URI is `silkit://0.0.0.0:8501`. That can't be right, that is the *any* IP address for listening sockets. You should put the IP address of the host running the registry there.

With WSL there's some subtle port forwarding and magic networking invovled.
You could try starting your registry on the WSL side:
```
./_build/linux-release/Release/sil-kit-registry --listen-uri silkit://0.0.0.0:8501
```
The use of the any-address is correct here.
Then you need to point your Windows participant to the localhost on port 8501:

```
Middleware:
  RegistryUri: silkit://localhost:8501
```

Let me know if that helps.

**Comment by MariusBgm** [comment] 2024-11-21 13:22
@MarcoJassy i cannot reproduce the nodelay errors, with your configs.
Could you provide some more infos:
- What kind of WSL do you run?
  e.g. what WSL imagedo you use? the output of  `uname -a` or `lsb_release -a` in the WSL shell.
- What WSL version?
   you can check that with `wsl --list --verbose` in a CMD/powershell prompt.

for what it's worth, I'm on a WSL version 2 running an Ubuntu 20.04 image.

**Comment by MarcoJassy** [comment] 2024-11-21 13:36
Well that is strange @MariusBgm. I am using windows 10 with WSL2 and Ubuntu 22.04. My SIL Kit version is 4.0.42.

**Comment by MariusBgm** [comment] 2024-11-21 13:40
> Well that is strange @MariusBgm. I am using windows 10 with WSL2 and Ubuntu 22.04. My SIL Kit version is 4.0.42.

@MarcoJassy I just attempted with SIL Kit Version 4.0.42, and it also works. I tested using the SilKit Ethernet Demo.
Did you use one of the SIL Kit Demos? If not, could you test with a bundled SIL Kit Demo with your configurations and report back? 
Or if you have custom code, are your participants using boost::asio themselves in their code?

**Comment by MarcoJassy** [comment] 2024-11-21 19:30
@MariusBgm, I started the registry of my test and than run SilKitDemoEthernet with the configuration yaml of my test as an EthernetWriter. The problem still showed up. Am I missing something in this setup?

**Comment by MariusBgm** [comment] 2024-11-22 06:41
@MarcoJassy with a WSL2 Ubuntu 22.04 I can reproduce a crash at startup, but not the no-delay issue. We'll investigate further. I'll keep you posted.
Meanwhile, could you try the latest SilKit 4.0.54 in your environment?

**Comment by MariusBgm** [comment] 2024-11-22 12:05
@MarcoJassy  We could reproduce the issue on Linux, it's a bug that was already fixed in commit https://github.com/vectorgrp/sil-kit/commit/545b2fb9f1180f2d2667165f1207aa31f33a525a . 
You should update to the latest SIL Kit version, if possible.

**Closed** 2024-11-25 08:31 UTC
